### ISSUE TITLE
Currency manipulation and conversion library

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Money#1]
- [x] objects for money and currency
- [x] doctrine type price
- [x] <del>safe multiplication of floats using php's math libraries</del> don't support floats
- [x] <del>reuse some project that provides interface for currency providers</del> (#3)
- [x] <del>create provider for CNB</del> (#3)
- [ ] formatters support (intl?)
